### Fontes
font_family       Fira Code
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         11.0
disable_ligatures never

### Tema e Aparência
include Dark_Pastel.conf
dynamic_background_opacity yes
background_opacity     1
background_blur        10
cursor_shape          block
cursor_beam_thickness 1.5
draw_minimal_borders  yes

### Performance
repaint_delay 8
input_delay   2
sync_to_monitor yes

### Clipboard
copy_on_select yes

### Scrollback
scrollback_lines 10000
scrollback_pager less --RAW-CONTROL-CHARS --quit-if-one-screen

### Abas e Janelas
window_padding_width 8
window_margin_width  5
window_border_width  1
active_tab_font_style bold
focus_follows_mouse yes
enabled_layouts splits, tall, fat, grid

### Layout da Janela do SO
remember_window_size  no
initial_window_width  640
initial_window_height 800

### Atalhos de Produtividade
# --- Atalhos Gerais ---
map ctrl+shift+e edit_config_file
map ctrl+shift+r load_config_file
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+l clear_terminal scroll active

### Terminal Bell
enable_audio_bell no
